### ISSUE TITLE
CheckVersion fails for version 0.2

### ISSUE THREAD

**Issue by ilpol984** [DebugBill/Link-Tap#1]
When plugin tries to check update it fails:
2023-09-21 11:49:45.887 Error: Irrigazione: A newer version of Link-Tap plugin is available: 0.1. Current version is: 0.2

As the api https://api.github.com/repos/DebugBill/Link-Tap/releases/latest returns the wrong version

{
  "url": "https://api.github.com/repos/DebugBill/Link-Tap/releases/45262099",
  "assets_url": "https://api.github.com/repos/DebugBill/Link-Tap/releases/45262099/assets",
  "upload_url": "https://uploads.github.com/repos/DebugBill/Link-Tap/releases/45262099/assets{?name,label}",
  "html_url": "https://github.com/DebugBill/Link-Tap/releases/tag/0.1",
  "id": 45262099,
  "author": {
    "login": "DebugBill",
    "id": 25805255,
    "node_id": "MDQ6VXNlcjI1ODA1MjU1",
    "avatar_url": "https://avatars.githubusercontent.com/u/25805255?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/DebugBill",
    "html_url": "https://github.com/DebugBill",
    "followers_url": "https://api.github.com/users/DebugBill/followers",
    "following_url": "https://api.github.com/users/DebugBill/following{/other_user}",
    "gists_url": "https://api.github.com/users/DebugBill/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/DebugBill/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/DebugBill/subscriptions",
    "organizations_url": "https://api.github.com/users/DebugBill/orgs",
    "repos_url": "https://api.github.com/users/DebugBill/repos",
    "events_url": "https://api.github.com/users/DebugBill/events{/privacy}",
    "received_events_url": "https://api.github.com/users/DebugBill/received_events",
    "type": "User",
    "site_admin": false
  },
  "node_id": "MDc6UmVsZWFzZTQ1MjYyMDk5",
  "tag_name": "0.1",
  "target_commitish": "main",
  "name": "Very first functionnal release in alpha stage",
  "draft": false,
  "prerelease": false,
  "created_at": "2021-06-25T22:01:23Z",
  "published_at": "2021-06-25T22:08:48Z",
  "assets": [

  ],
  "tarball_url": "https://api.github.com/repos/DebugBill/Link-Tap/tarball/0.1",
  "zipball_url": "https://api.github.com/repos/DebugBill/Link-Tap/zipball/0.1",
  "body": "This is the very first official release of the Link-Tap plugin. Consider it as \"alpha\" even though it seems to work as expected.\r\n\r\nDon't hesiate to report issues."
}

Can you please fix this?

Thank you, regards,

**Comment by DebugBill** [comment]
Hi,
Sorry for the delay. It is now fixed
